[package]
name = "view_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rocksdb = "0.18.0"
tokio-tungstenite = "0.17.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
